#!/bin/bash

if [ -f /etc/default/cyanite ]; then
    . /etc/default/cyanite
fi

JAR="$EXTRA_CLASSPATH:/usr/lib/cyanite/cyanite.jar"
CONFIG="/etc/cyanite.yaml"
AGGRESSIVE_OPTS="-XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:+UseCompressedOops"

usage()
{
  cat << EOF
usage: $0 [-a] [java options ...] [-f config-file]

Runs Cyanite with the given configuration file.

OPTIONS:
  -h    Show this message
  -a    Adds some default aggressive, nonportable JVM optimization flags.

  Any unrecognized options (e.g. -XX:+UseParNewGC) will be passed on to java.
EOF
}

OPTS=
for arg in "$@"; do
  case $arg in
    "-a")
      OPTS="$AGGRESSIVE_OPTS $OPTS"
      ;;
    "-h")
      usage
      exit 0
      ;;
    -*)
      OPTS="$OPTS $arg"
      ;;
    *)
      CONFIG="$arg"
     ;;
  esac
done

exec java $EXTRA_JAVA_OPTS $OPTS -cp "$JAR" riemann.bin "$CONFIG"